$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
# display_name: nyc_taxi_data_regression #usually better to leave this out tbh so you get unique names. 
experiment_name: nyc-taxi-pipeline
description: Train regression model based on nyc taxi dataset

# <inputs_and_outputs>
outputs: 
  pipeline_job_trained_model:
    type: mlflow_model
    mode: rw_mount
  pipeline_job_predictions:
    mode: rw_mount 
  pipeline_job_score_report:
    mode: rw_mount
# </inputs_and_outputs>

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:sample-managed-id-cluster
  continue_on_step_failure: false

jobs:
  merge_job:
    type: command
    code: ../code/merge_data
    command: >-
      python test.py
      --raw_data_train ${{inputs.raw_data_train}}
      --raw_data_val ${{inputs.raw_data_val}}
      --processed_data ${{outputs.processed_data}}
    inputs:
      raw_data_train:
        type: uri_file 
        path: azureml:intent_class_train@latest
      raw_data_val:
        type: uri_file 
        path: azureml:intent_class_validation@latest
    outputs:
      processed_data:
        mode: upload
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240304.v1
      conda_file: ../environments/conda.yaml
